In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [ ]:
%cd /gdrive/MyDrive/Parkinson/dataset

/gdrive/.shortcut-targets-by-id/12nqRIruOFAC5bojzeVDsLTEyrWBsPUR0/Parkinson/dataset


In [ ]:
ls

Backup/                 parkinson.csv          parkinson_std_norm.csv
normalizeDataset.ipynb  parkinson_min_max.csv
parkinson_bat.csv       parkinson_pso.csv


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
p=pd.read_csv('parkinson_min_max.csv')

In [ ]:
p.head()

Unnamed: 0  gender  ...  tqwt_kurtosisValue_dec_36  class
0           0     1.0  ...                   0.107598      1
1           1     1.0  ...                   0.277905      1
2           2     1.0  ...                   0.015595      1
3           3     0.0  ...                   0.011011      1
4           4     0.0  ...                   0.024357      1

[5 rows x 755 columns]

In [ ]:
x_df=p.drop(['Unnamed: 0','class'],axis=1)
y_df=p['class']
x_df.head()

gender       PPE  ...  tqwt_kurtosisValue_dec_35  tqwt_kurtosisValue_dec_36
0     1.0  0.936278  ...                   0.018790                   0.107598
1     1.0  0.837434  ...                   0.078923                   0.277905
2     1.0  0.934385  ...                   0.021472                   0.015595
3     0.0  0.426804  ...                   0.077518                   0.011011
4     0.0  0.330615  ...                   0.055767                   0.024357

[5 rows x 753 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_Train, X_Test, y_train, y_test = train_test_split(x_df, y_df, test_size=0.2, random_state=17)

In [ ]:
# Fitting the classifier into the Training set
from sklearn.ensemble import RandomForestClassifier

In [ ]:
Classifier=RandomForestClassifier()

In [ ]:
## Hyper Parameter tuning
n_estimators = [60,80, 100, 500, 900, 1100]
criterion=['gini','entropy']
max_depth = [10,15,20,25,30]

# Define the grid of hyperparameters to search
hyperparameter_grid = {
    'n_estimators': n_estimators,
    'max_depth':max_depth,
    'criterion':criterion
    }

In [ ]:
from sklearn.model_selection import RandomizedSearchCV 
random_cv = RandomizedSearchCV(estimator=Classifier,
            param_distributions=hyperparameter_grid,
            cv=5, n_iter=50,
            scoring = 'neg_mean_absolute_error',n_jobs = 4,
            verbose = 5, 
            return_train_score = True,
            random_state=17)

In [ ]:
random_cv.fit(X_Train,y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  10 tasks      | elapsed:  1.3min
[Parallel(n_jobs=4)]: Done  64 tasks      | elapsed:  4.4min
[Parallel(n_jobs=4)]: Done 154 tasks      | elapsed:  8.3min
[Parallel(n_jobs=4)]: Done 250 out of 250 | elapsed: 13.1min finished


RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
               

In [ ]:
random_cv.best_estimator_

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=20, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=80,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
Classifier = RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=20, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=82,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
Classifier.fit(X_Train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=20, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=82,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred=Classifier.predict(X_Test)

In [ ]:
y_pred

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
tes=np.array(y_test)
tes

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [ ]:
np.sum(np.abs(tes-y_pred))

23

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred,tes)
cm

array([[ 20,   5],
       [ 18, 109]])

In [ ]:
%cd /gdrive/MyDrive/Parkinson/rf/Rushi/Model

/gdrive/.shortcut-targets-by-id/12nqRIruOFAC5bojzeVDsLTEyrWBsPUR0/Parkinson/rf/Rushi/Model


In [ ]:
pwd

'/gdrive/.shortcut-targets-by-id/12nqRIruOFAC5bojzeVDsLTEyrWBsPUR0/Parkinson/rf/Rushi/Model'

In [ ]:
import pickle
filename = 'model_rf_rushi_minmax.pkl'
pickle.dump(Classifier, open(filename, 'wb'))